# Generated by Django 3.1.5 on 2021-03-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
