# Generated by Django 3.1.5 on 2021-05-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('cheap', models.CharField(max_length=255)),
                ('badelog', models.CharField(max_length=255)),
                ('randirona', models.CharField(max_length=255)),
                ('active', models.CharField(max_length=255)),
            ],
        ),
    ]
